version: '3.9'

services:
  db:
    image: postgres:latest
    restart: always
    env_file:
      - ".env"    
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}      
    ports: 
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    env_file:
      - ".env"       
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'True'
      PGADMIN_ENABLE_CSRF_PROTECTION: 'True'
      PGADMIN_SERVER_JSON_DATA: 
        '[{"Name": "pg", 
        "Group": "Servers", 
        "Port": 5432, 
        "Username": "postgres", 
        "Password": "${DB_PASSWORD}", 
        "Host": "db", 
        "SSLMode": "prefer", 
        "MaintenanceDB": "${DB_NAME}", 
        "DBRestriction": "${DB_NAME}"
        }]'
    restart: always
volumes:
  db-data:






