version: '3.9'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}      
    ports: 
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: nikitaprudov@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: always    
volumes:
  db-data:    

    # networks:
    # - tg_bot 

  # bot:
  #   image: "${BOT_IMAGE_NAME:-tg_bot-image}"
  #   container_name: "${BOT_CONTAINER_NAME:-tg_bot-container}"
  #   stop_signal: SIGINT
  #   build:
  #     context: .
  #   depends_on:
  #     - db      
  #   working_dir: "/usr/src/app/${BOT_NAME:-tg_bot}"
  #   volumes:
  #   - .:/usr/src/app/${BOT_NAME:-tg_bot}
  #   command: python3 -m app
  #   restart: always
  #   env_file:
  #     - ".env"
  #   environment:
  #     BOT_TOKEN: ${BOT_TOKEN}
  #     DB_HOST: db
  #     DB_PORT: ${DB_PORT}
  #     DB_NAME: ${DB_NAME}
  #     DB_USER: ${DB_USER}
  #     DB_PASSWORD: ${DB_PASSWORD}      
  #   networks:
  #   - tg_bot
  #   ports:
  #     - "80:80"    

# networks:
#   tg_bot:
#     driver: bridge

