version: '3.9'

services:
  bot:
    image: "${BOT_IMAGE_NAME:-image}"
    container_name: "${BOT_CONTAINER_NAME:-container}"
    stop_signal: SIGINT
    build:
      context: .  
    working_dir: "/usr/src/app/${BOT_NAME}"
    volumes:
    - .:/usr/src/app/${BOT_NAME}
    command: python3 -m app
    restart: always
    env_file:
      - ".env"
    environment:
      BOT_TOKEN: ${BOT_TOKEN}  
      MQTT_HOST: ${MQTT_HOST}
      MQTT_PORT: ${MQTT_PORT}
    networks:
    - tg_bot
    ports:
      - "8080:80"   

volumes:
  db-data:
  
networks:
  tg_bot:
    driver: bridge



