version: '3.9'

services:
  db:
    image: postgres:latest
    restart: always
    env_file:
      - ".env"    
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}      
    ports: 
      - "${DB_PORT}:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - tg_bot

  bot:
    image: "${BOT_IMAGE_NAME:-image}"
    container_name: "${BOT_CONTAINER_NAME:-container}"
    stop_signal: SIGINT
    build:
      context: .
    depends_on:
      - db      
    working_dir: "/usr/src/app/${BOT_NAME}"
    volumes:
    - .:/usr/src/app/${BOT_NAME}
    command: python3 -m app
    restart: always
    env_file:
      - ".env"
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}    
      MQTT_HOST: ${MQTT_HOST}
      MQTT_PORT: ${MQTT_PORT}
    networks:
    - tg_bot
    ports:
      - "8080:80"   

volumes:
  db-data:
  
networks:
  tg_bot:
    driver: bridge



