
services:
  bot:
    image: "${BOT_IMAGE_NAME:-image}"
    container_name: "${BOT_CONTAINER_NAME:-container}"
    stop_signal: SIGINT
    build:
      context: .  
    working_dir: "/mnt/data/${BOT_NAME:-app}"
    volumes:
    - .:/mnt/data/${BOT_NAME}
    command: python3 -m app
    restart: always
    env_file:
      - ".env"
    environment:
      BOT_TOKEN: ${BOT_TOKEN}  
      MQTT_HOST: ${MQTT_HOST}
      MQTT_PORT: ${MQTT_PORT}
    networks:
    - wb-bot
    ports:
      - "8080:80"   

volumes:
  db-data:
  
networks:
  wb-bot:
    driver: bridge



